
name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Configuring Github Actions'
        default: 'World'
        required: true

jobs:
  manual:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      CTEST_OUTPUT_ON_FAILURE: ON
      CTEST_PARALLEL_LEVEL: 2
    strategy:
      fail-fast: false
      matrix:
        name: [
          ubuntu-18.04-gcc-7,
          ubuntu-latest-gcc-10,
        ]
        include:
          - name: ubuntu-18.04-gcc-7
            os: ubuntu-18.04
            compiler: gcc
            version: "7"
            
          - name: ubuntu-latest-gcc-10
            os: ubuntu-latest
            compiler: gcc
            version: "10"

    steps:
      - uses: actions/checkout@v2

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          echo "Running Job of gcc-${{matrix.version}} in ${{matrix.name}}"
          sudo apt-get install gcc-${{matrix.version}}
            
      - name: Build & Test Debug x64
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Debug --target alglin-tests
          cmake --build . --config Debug --target attdet-tests
          ctest

      - name: Build & Test Release x64
        run: |
          cd build
          cmake ..
          cmake --build . --config Release --target alglin-tests
          cmake --build . --config Release --target attdet-tests
          ctest
          